# Copyright 2026 Tony Meyer
# See LICENSE file for licensing details.

name: Charm CI

on:
  push:
    branches: [main]
    paths:
      - "charm/**"
      - ".github/workflows/charm.yaml"
  pull_request:
    paths:
      - "charm/**"
      - ".github/workflows/charm.yaml"

jobs:
  format-check:
    name: Format check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: charm
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: astral-sh/setup-uv@6b9c6063abd6010835c3c7f4a7d943c6e3ff714f # v6.0.1
      - run: uv run ruff format --check --diff src tests
      - run: uv run ruff check src tests

  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: charm
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: astral-sh/setup-uv@6b9c6063abd6010835c3c7f4a7d943c6e3ff714f # v6.0.1
      - run: uv run codespell .
      - run: uv run ty check

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: charm
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: astral-sh/setup-uv@6b9c6063abd6010835c3c7f4a7d943c6e3ff714f # v6.0.1
      - run: |
          uv run coverage run --source=src -m pytest -v -s --tb native tests/unit
          uv run coverage report

  integration-test:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: [format-check, lint, unit-test]
    defaults:
      run:
        working-directory: charm
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: astral-sh/setup-uv@6b9c6063abd6010835c3c7f4a7d943c6e3ff714f # v6.0.1
      - name: Set up Juju
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
      - name: Pack charm
        run: charmcraft pack
      - name: Run integration tests
        run: uv run pytest -v -s --tb native --log-cli-level=INFO tests/integration
