# Copyright 2026 Tony Meyer
# See LICENSE file for licensing details.
# uv version resolved from root uv.toml

name: Workload CI

on:
  push:
    branches: [main]
    paths:
      - "workload/**"
      - ".github/workflows/workload.yaml"
  pull_request:
    paths:
      - "workload/**"
      - ".github/workflows/workload.yaml"

permissions:
  contents: read

jobs:
  format-check:
    name: Format check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: workload
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      - run: uv run ruff format --check --diff src
      - run: uv run ruff check src

  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: workload
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      - run: uv run ty check src/

  test:
    name: Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: workload
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      - run: |
          uv run coverage run --source=src -m pytest -v -s --tb native tests/
          uv run coverage report
