# Copyright 2026 Tony Meyer
# See LICENSE file for licensing details.

name: Workload CI

on:
  push:
    branches: [main]
    paths:
      - "workload/**"
      - ".github/workflows/workload.yaml"
  pull_request:
    paths:
      - "workload/**"
      - ".github/workflows/workload.yaml"

jobs:
  format-check:
    name: Format check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: workload
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: astral-sh/setup-uv@6b9c6063abd6010835c3c7f4a7d943c6e3ff714f # v6.0.1
      - run: uv run ruff format --check --diff src
      - run: uv run ruff check src

  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: workload
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: astral-sh/setup-uv@6b9c6063abd6010835c3c7f4a7d943c6e3ff714f # v6.0.1
      - run: uv run ty check

  test:
    name: Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: workload
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: astral-sh/setup-uv@6b9c6063abd6010835c3c7f4a7d943c6e3ff714f # v6.0.1
      - run: |
          uv run coverage run --source=src -m pytest -v -s --tb native tests/
          uv run coverage report
